import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    exclude: ['**/node_modules/**', '**/dist/**', '**/test/**'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov', 'json', 'json-summary'],
      reportsDirectory: './coverage',
      include: [
        'src/**/*.ts',
        'core/**/*.ts',
        'ui/**/*.ts',
      ],
      exclude: [
        '**/__tests__/**',
        '**/__benchmarks__/**',
        '**/*.test.ts',
        '**/*.bench.ts',
        '**/*.d.ts',
        '**/node_modules/**',
        '**/dist/**',
        '**/test/**',
        'src/examples/**',
        'src/cli/**',
        'src/adapters/**',
        'src/index.ts',
        'src/index.browser.ts',
        'src/dsl.ts',
        'src/flows.ts',
        'src/step.ts',
        'src/registry.ts',
        'src/chronos/index.ts',
        'src/conversations/index.ts',
        'src/conversations/types.ts',
        'src/core/chronicle/index.ts',
        'src/core/reactive-engine.svelte.ts',
        'src/chronos-bridge/**',
        'src/causal-anomaly/**',
        'src/uncertainty/**',
        'src/cloud/auth.ts',
        'src/cloud/marketplace.ts',
        'src/cloud/relay/**',
        'src/hooks/context.ts',
        'src/hooks/install.ts',
        'src/integrations/unified.ts',
        'ui/svelte-generator/**',
        'ui/canvas-inspector/**',
        'core/codegen/index.ts',
        'core/db-adapter/**',
        'core/logic-engine/**',
        'core/schema-engine/index.ts',
        'core/schema-engine/types.ts',
      ],
      thresholds: {
        statements: 80,
        lines: 80,
        functions: 75,
        branches: 60,
      },
    },
  },
});
