name: Feature Request / Enhancement
description: Suggest a new feature or enhancement for Praxis
title: "[Enhancement]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an enhancement! Please provide details below.
  
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What area does this enhancement relate to?
      options:
        - Core Framework
        - Schema System
        - Logic Engine
        - Component Generator
        - CLI Tools
        - Documentation
        - Integration (PluresDB, Unum, etc.)
        - Developer Experience
        - Other
    validations:
      required: true
  
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem or limitation you're experiencing
      placeholder: What problem does this solve?
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you'd like this to work
      placeholder: What would you like to see added or changed?
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered
  
  - type: textarea
    id: examples
    attributes:
      label: Example Usage
      description: Show how you'd use this feature
      render: typescript
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or references
