/* eslint-disable */
/* auto-generated by NAPI-RS */
/* tslint:disable */

const { existsSync, readFileSync } = require('fs');
const { join } = require('path');

const { platform, arch } = process;

let nativeBinding = null;
let localFileExisted = false;
let loadError = null;

function isMusl() {
  // For Node.js 12+, use `process.report.getReport()` instead of reading /proc
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process')
        .execSync('which ldd')
        .toString()
        .trim();
      return readFileSync(lddPath, 'utf8').includes('musl');
    } catch {
      return true;
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header;
    return !glibcVersionRuntime;
  }
}

switch (platform) {
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'praxis-native.win32-x64-msvc.node')
        );
        try {
          if (localFileExisted) {
            nativeBinding = require('./praxis-native.win32-x64-msvc.node');
          } else {
            nativeBinding = require('@plures/praxis-native-win32-x64-msvc');
          }
        } catch (e) {
          loadError = e;
        }
        break;
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`);
    }
    break;
  case 'darwin':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'praxis-native.darwin-x64.node')
        );
        try {
          if (localFileExisted) {
            nativeBinding = require('./praxis-native.darwin-x64.node');
          } else {
            nativeBinding = require('@plures/praxis-native-darwin-x64');
          }
        } catch (e) {
          loadError = e;
        }
        break;
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'praxis-native.darwin-arm64.node')
        );
        try {
          if (localFileExisted) {
            nativeBinding = require('./praxis-native.darwin-arm64.node');
          } else {
            nativeBinding = require('@plures/praxis-native-darwin-arm64');
          }
        } catch (e) {
          loadError = e;
        }
        break;
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`);
    }
    break;
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'praxis-native.linux-x64-musl.node')
          );
          try {
            if (localFileExisted) {
              nativeBinding = require('./praxis-native.linux-x64-musl.node');
            } else {
              nativeBinding = require('@plures/praxis-native-linux-x64-musl');
            }
          } catch (e) {
            loadError = e;
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'praxis-native.linux-x64-gnu.node')
          );
          try {
            if (localFileExisted) {
              nativeBinding = require('./praxis-native.linux-x64-gnu.node');
            } else {
              nativeBinding = require('@plures/praxis-native-linux-x64-gnu');
            }
          } catch (e) {
            loadError = e;
          }
        }
        break;
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'praxis-native.linux-arm64-musl.node')
          );
          try {
            if (localFileExisted) {
              nativeBinding = require('./praxis-native.linux-arm64-musl.node');
            } else {
              nativeBinding = require('@plures/praxis-native-linux-arm64-musl');
            }
          } catch (e) {
            loadError = e;
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'praxis-native.linux-arm64-gnu.node')
          );
          try {
            if (localFileExisted) {
              nativeBinding = require('./praxis-native.linux-arm64-gnu.node');
            } else {
              nativeBinding = require('@plures/praxis-native-linux-arm64-gnu');
            }
          } catch (e) {
            loadError = e;
          }
        }
        break;
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`);
    }
    break;
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`);
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError;
  }
  throw new Error('Failed to load native binding');
}

const { parse, compile, lint, execute, listNativeFunctions, compileWithLint } =
  nativeBinding;

module.exports.parse = parse;
module.exports.compile = compile;
module.exports.lint = lint;
module.exports.execute = execute;
module.exports.listNativeFunctions = listNativeFunctions;
module.exports.compileWithLint = compileWithLint;
