/* auto-generated by NAPI-RS */
/* eslint-disable */
/* tslint:disable */

/** Parse a .px file and return the AST as JSON */
export declare function parse(source: string): string;

/** Compile a .px file to PluresDB records (JSON) */
export declare function compile(source: string): string;

/** Lint a .px file and return diagnostics as JSON */
export declare function lint(source: string): string;

/** Execute a compiled procedure with the given context (JSON) */
export declare function execute(compiledJson: string, contextJson: string): string;

/** List all available native functions registered in the runtime */
export declare function listNativeFunctions(): string;

/** Compile a .px file with lint diagnostics included */
export declare function compileWithLint(source: string): string;
